{% set name = "types-setuptools" %}
{% set version = "65.5.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-setuptools-{{ version }}.tar.gz
  sha256: 2338bc809c925579c3bb5656a77d5713eafe51e384dcaca7b33f70b8e9d02885

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/pkg_resources-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for setuptools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
