{% set name = "types-setuptools" %}
{% set version = "80.9.0.20251223" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d3411059ae2f5f03985217d86ac6084efea2c9e9cacd5f0869ef950f308169b2

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

test:
  requires:
    - pip
    - setuptools  # [py>=314]
  imports:
    - setuptools
  commands:
    - pip check
    - test -f $SP_DIR/pkg_resources/__init__.py  # [unix]
    - test -f $SP_DIR/setuptools-stubs/__init__.pyi  # [unix]
    - test -f $SP_DIR/distutils-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\pkg_resources\\__init__.py exit 1  # [win]
    - if not exist %SP_DIR%\\setuptools-stubs\\__init__.pyi exit 1  # [win]
    - if not exist %SP_DIR%\\distutils-stubs\\__init__.pyi exit 1  # [win]
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/python/typeshed
  description: Typing stubs for setuptools
  summary: Typing stubs for setuptools
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  license_family: Other
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
